/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SpelvalutaRouteImport } from './routes/spelvaluta'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin-live'
import { Route as AuthenticatedButikRouteImport } from './routes/_authenticated/butik'
import { Route as AuthenticatedHemRouteImport } from './routes/_authenticated/hem'
import { Route as AuthenticatedInstallningarRouteImport } from './routes/_authenticated/installningar'
import { Route as AuthenticatedKartaRouteImport } from './routes/_authenticated/karta'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedNotiserRouteImport } from './routes/_authenticated/notiser'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedSocialtRouteImport } from './routes/_authenticated/socialt'
import { Route as AuthenticatedTopplistaRouteImport } from './routes/_authenticated/topplista'
import { Route as AuthenticatedUppdragRouteImport } from './routes/_authenticated/uppdrag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SpelvalutaRoute = SpelvalutaRouteImport.update({
  id: '/spelvaluta',
  path: '/spelvaluta',
  getParentRoute: () => rootRouteImport,
} as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/admin-live',
  path: '/admin-live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedButikRoute = AuthenticatedButikRouteImport.update({
  id: '/butik',
  path: '/butik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHemRoute = AuthenticatedHemRouteImport.update({
  id: '/hem',
  path: '/hem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstallningarRoute =
  AuthenticatedInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKartaRoute = AuthenticatedKartaRouteImport.update({
  id: '/karta',
  path: '/karta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotiserRoute = AuthenticatedNotiserRouteImport.update({
  id: '/notiser',
  path: '/notiser',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSocialtRoute = AuthenticatedSocialtRouteImport.update({
  id: '/socialt',
  path: '/socialt',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopplistaRoute = AuthenticatedTopplistaRouteImport.update({
  id: '/topplista',
  path: '/topplista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUppdragRoute = AuthenticatedUppdragRouteImport.update({
  id: '/uppdrag',
  path: '/uppdrag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integritet': typeof IntegritetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/spelvaluta': typeof SpelvalutaRoute
  '/villkor': typeof VillkorRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-live': typeof AuthenticatedAdminLiveRoute
  '/butik': typeof AuthenticatedButikRoute
  '/hem': typeof AuthenticatedHemRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/karta': typeof AuthenticatedKartaRoute
  '/live': typeof AuthenticatedLiveRoute
  '/notiser': typeof AuthenticatedNotiserRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/socialt': typeof AuthenticatedSocialtRoute
  '/topplista': typeof AuthenticatedTopplistaRoute
  '/uppdrag': typeof AuthenticatedUppdragRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/integritet': typeof IntegritetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/spelvaluta': typeof SpelvalutaRoute
  '/villkor': typeof VillkorRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-live': typeof AuthenticatedAdminLiveRoute
  '/butik': typeof AuthenticatedButikRoute
  '/hem': typeof AuthenticatedHemRoute
  '/installningar': typeof AuthenticatedInstallningarRoute
  '/karta': typeof AuthenticatedKartaRoute
  '/live': typeof AuthenticatedLiveRoute
  '/notiser': typeof AuthenticatedNotiserRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/socialt': typeof AuthenticatedSocialtRoute
  '/topplista': typeof AuthenticatedTopplistaRoute
  '/uppdrag': typeof AuthenticatedUppdragRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integritet': typeof IntegritetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/spelvaluta': typeof SpelvalutaRoute
  '/villkor': typeof VillkorRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/butik': typeof AuthenticatedButikRoute
  '/_authenticated/hem': typeof AuthenticatedHemRoute
  '/_authenticated/installningar': typeof AuthenticatedInstallningarRoute
  '/_authenticated/karta': typeof AuthenticatedKartaRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/notiser': typeof AuthenticatedNotiserRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/socialt': typeof AuthenticatedSocialtRoute
  '/_authenticated/topplista': typeof AuthenticatedTopplistaRoute
  '/_authenticated/uppdrag': typeof AuthenticatedUppdragRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/integritet'
    | '/reset-password'
    | '/spelvaluta'
    | '/villkor'
    | '/admin'
    | '/admin-live'
    | '/butik'
    | '/hem'
    | '/installningar'
    | '/karta'
    | '/live'
    | '/notiser'
    | '/onboarding'
    | '/profil'
    | '/socialt'
    | '/topplista'
    | '/uppdrag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/integritet'
    | '/reset-password'
    | '/spelvaluta'
    | '/villkor'
    | '/admin'
    | '/admin-live'
    | '/butik'
    | '/hem'
    | '/installningar'
    | '/karta'
    | '/live'
    | '/notiser'
    | '/onboarding'
    | '/profil'
    | '/socialt'
    | '/topplista'
    | '/uppdrag'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/integritet'
    | '/reset-password'
    | '/spelvaluta'
    | '/villkor'
    | '/_authenticated/admin'
    | '/_authenticated/admin-live'
    | '/_authenticated/butik'
    | '/_authenticated/hem'
    | '/_authenticated/installningar'
    | '/_authenticated/karta'
    | '/_authenticated/live'
    | '/_authenticated/notiser'
    | '/_authenticated/onboarding'
    | '/_authenticated/profil'
    | '/_authenticated/socialt'
    | '/_authenticated/topplista'
    | '/_authenticated/uppdrag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntegritetRoute: typeof IntegritetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SpelvalutaRoute: typeof SpelvalutaRoute
  VillkorRoute: typeof VillkorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spelvaluta': {
      id: '/spelvaluta'
      path: '/spelvaluta'
      fullPath: '/spelvaluta'
      preLoaderRoute: typeof SpelvalutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-live': {
      id: '/_authenticated/admin-live'
      path: '/admin-live'
      fullPath: '/admin-live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/butik': {
      id: '/_authenticated/butik'
      path: '/butik'
      fullPath: '/butik'
      preLoaderRoute: typeof AuthenticatedButikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hem': {
      id: '/_authenticated/hem'
      path: '/hem'
      fullPath: '/hem'
      preLoaderRoute: typeof AuthenticatedHemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/installningar': {
      id: '/_authenticated/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof AuthenticatedInstallningarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karta': {
      id: '/_authenticated/karta'
      path: '/karta'
      fullPath: '/karta'
      preLoaderRoute: typeof AuthenticatedKartaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notiser': {
      id: '/_authenticated/notiser'
      path: '/notiser'
      fullPath: '/notiser'
      preLoaderRoute: typeof AuthenticatedNotiserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/socialt': {
      id: '/_authenticated/socialt'
      path: '/socialt'
      fullPath: '/socialt'
      preLoaderRoute: typeof AuthenticatedSocialtRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topplista': {
      id: '/_authenticated/topplista'
      path: '/topplista'
      fullPath: '/topplista'
      preLoaderRoute: typeof AuthenticatedTopplistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/uppdrag': {
      id: '/_authenticated/uppdrag'
      path: '/uppdrag'
      fullPath: '/uppdrag'
      preLoaderRoute: typeof AuthenticatedUppdragRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedButikRoute: typeof AuthenticatedButikRoute
  AuthenticatedHemRoute: typeof AuthenticatedHemRoute
  AuthenticatedInstallningarRoute: typeof AuthenticatedInstallningarRoute
  AuthenticatedKartaRoute: typeof AuthenticatedKartaRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedNotiserRoute: typeof AuthenticatedNotiserRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedSocialtRoute: typeof AuthenticatedSocialtRoute
  AuthenticatedTopplistaRoute: typeof AuthenticatedTopplistaRoute
  AuthenticatedUppdragRoute: typeof AuthenticatedUppdragRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
  AuthenticatedButikRoute: AuthenticatedButikRoute,
  AuthenticatedHemRoute: AuthenticatedHemRoute,
  AuthenticatedInstallningarRoute: AuthenticatedInstallningarRoute,
  AuthenticatedKartaRoute: AuthenticatedKartaRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedNotiserRoute: AuthenticatedNotiserRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedSocialtRoute: AuthenticatedSocialtRoute,
  AuthenticatedTopplistaRoute: AuthenticatedTopplistaRoute,
  AuthenticatedUppdragRoute: AuthenticatedUppdragRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntegritetRoute: IntegritetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SpelvalutaRoute: SpelvalutaRoute,
  VillkorRoute: VillkorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
